#!/usr/bin/bash
# Run random gradient background daemon
function snore()
{
    local IFS
    [[ -n "${_snore_fd:-}" ]] || exec {_snore_fd}<> <(:)
    read ${1:+-t "$1"} -u $_snore_fd || :
}

while gbg; do
    snore 300			# randomize every 5min
done
